# Generated by Django 3.1.4 on 2020-12-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201227_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='markets',
        ),
    ]
