# Generated by Django 3.1.4 on 2020-12-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_sport_number_of_participants'),
        ('markets', '0002_auto_20201227_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='sport',
            field=models.ForeignKey(default=221, on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
            preserve_default=False,
        ),
    ]
